# Generated by Django 4.0.2 on 2024-04-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('tickerId', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticketType', models.CharField(max_length=50)),
                ('availableSeats', models.IntegerField()),
            ],
        ),
    ]
