version: '3.9'
services:
  be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    # environment:
    #   - DB_TYPE=mysql
    #   - MYSQL_HOST=db
    #   - MYSQL_USER=root
    #   - MYSQL_PASSWORD=root
    #   - MYSQL_DATABASE=admin
    #   - MYSQL_PORT=3306
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    # restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=admin
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=localhost
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: {}
